name: Sync Fork

on:
  schedule:
    - cron: '0 */3 * * *'   # 每三小时执行一次（UTC 时间）
  workflow_dispatch:       # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/huangxd-/danmu_api.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Sync upstream changes (ignore workflows)
        run: |
          git checkout upstream/main -- .
          rm -rf .github/workflows
          git commit -am "sync from upstream (without workflows)" || echo "No changes"

      - name: Push changes
        run: git push origin main